version: "3.3"

services:
  app:
    image: sitepilot/runtime:latest
    depends_on:
      - db
      - redis
    ports:
      - "9080:8080"
    restart: always
    volumes:
      - "app_data:/opt/sitepilot/app"
    environment:
      APP_ENV: production
      DB_NAME: app
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: secret
      DEPLOY_TOKEN: supersecret
      DEPLOY_REPOSITORY: https://github.com/sitepilot/project-wordpress.git

  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: supersecret

  redis:
    image: redis:6-alpine

volumes:
  db_data:
  app_data:
